- name: create job for short SMART test
  ansible.builtin.cron:
    name: "daily SMART test short {{ item }}"
    special_time: "daily"
    job: "smartctl -t short {{ item }}"
    state: present
    user: root
  with_items:
    - "{{ nvme_device }}"
    - "{{ hdd_device1 }}"
    - "{{ hdd_device2 }}"

- name: create job for long SMART test
  ansible.builtin.cron:
    name: "weekly SMART test long {{ item }}"
    special_time: "weekly"
    job: "smartctl -t long {{ item }}"
    state: present
    user: root
  with_items:
    - "{{ nvme_device }}"
    - "{{ hdd_device1 }}"
    - "{{ hdd_device2 }}"

- name: add btrfs subvolumes for snapshots
  community.general.btrfs_subvolume:
    name: /snapshots
    state: present
    filesystem_label: "{{ item }}"
  with_items:
    - "{{ nvme_filesystem_label }}"
    - "{{ hdd_filesystem_label }}"

- name: create job for daily btrfs snapshots of apps
  ansible.builtin.cron:
    name: "daily btrfs snapshot of apps"
    special_time: "daily"
    job: "btrfs subvolume snapshot -r {{ nvme_mount_point }} {{ nvme_mount_point }}/snapshots/apps-$(date +\"%Y-%m-%d\")"
    state: present
    user: root

- name: create job daily btrfs snapshots of data
  ansible.builtin.cron:
    name: "daily btrfs snapshot of data"
    special_time: "daily"
    job: "btrfs subvolume snapshot -r {{ hdd_mount_point }} {{ hdd_mount_point }}/snapshots/data-$(date +\"%Y-%m-%d\")"
    state: present
    user: root

- name: create job for deleting snapshots of apps older than 30 days
  ansible.builtin.cron:
    name: "daily cleanup of old snapshots for apps (> 30 days)"
    special_time: "daily"
    job: "find {{ nvme_mount_point }}/snapshots -maxdepth 1 -mindepth 1 -type d -mtime +30 -exec btrfs subvolume delete {} \\;"
    state: present
    user: root

- name: create job for deleting snapshots of data older than 30 days
  ansible.builtin.cron:
    name: "daily cleanup of old snapshots for data (> 30 days)"
    special_time: "daily"
    job: "find {{ hdd_mount_point }}/snapshots -maxdepth 1 -mindepth 1 -type d -mtime +30 -exec btrfs subvolume delete {} \\;"
    state: present
    user: root

- name: create job for weekly rsync of {{ nvme_mount_point }}
  ansible.builtin.cron:
    name: "weekly rsync of {{ nvme_mount_point }}"
    special_time: "weekly"
    job: "rsync -rlvzq --delete --stats --progress --numeric-ids --log-file=/var/log/rsync-{{ nvme_filesystem_label }}.log -e 'ssh -p23 -i /home/{{ username }}/.ssh/id_ed25519' {{ nvme_mount_point }} {{ storage_box_address }}:/home"
    state: present
    user: root

- name: create job for weekly rsync of {{ hdd_mount_point }}
  ansible.builtin.cron:
    name: "weekly rsync of {{ hdd_mount_point }}"
    special_time: "weekly"
    job: "rsync -rlvzq --delete --stats --progress --numeric-ids --log-file=/var/log/rsync-{{ hdd_filesystem_label }}.log -e 'ssh -p23 -i /home/{{ username }}/.ssh/id_ed25519' {{ hdd_mount_point }} {{ storage_box_address }}:/home"
    state: present
    user: root