- name: SMART
  ansible.builtin.import_tasks:
    file: smart.yml

- name: Snapshots
  ansible.builtin.import_tasks:
    file: snapshots.yml

- name: Backup
  ansible.builtin.import_tasks:
    file: backup.yml

- name: Scrub
  ansible.builtin.import_tasks:
    file: scrub.yml

- name: Updates
  ansible.builtin.import_tasks:
    file: updates.yml