hostname: datacore

packages:
  - nano
  - htop
  - dnf-plugins-core
  - dnf-automatic
  - smartmontools
  - rsync
  - hyfetch
  - borgbackup
  - postfix
  - mailx

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

nvme_device: /dev/nvme0n1
hdd_device1: /dev/sdb
hdd_device2: /dev/sdc

nvme_mount_point: /mnt/nymph
hdd_mount_point: /mnt/siren

nvme_mount_point_name: nymph
hdd_mount_point_name: siren

nvme_filesystem_label: apps
hdd_filesystem_label: data

immich_postgres_db_hostname: immich-postgres
immich_postgres_db_name: immich
immich_postgres_db_user: postgres

nextcloud_mariadb_db_name: nextcloud
nextcloud_mariadb_db_user: nextcloud
