- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  notify: close default SSH port

- name: close default SSH port
  ansible.builtin.firewalld:
    port: 22/tcp
    permanent: yes
    state: disabled
    immediate: true

- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted