- name: add btrfs subvolumes for FreshRSS
  community.general.btrfs_subvolume:
    name: /freshrss
    state: present
    filesystem_label: "{{ nvme_filesystem_label }}"

- name: deploy FreshRSS
  community.docker.docker_container:
    name: freshrss
    image: freshrss/freshrss:latest
    restart_policy: unless-stopped
    volumes:
      - "{{ nvme_mount_point }}/freshrss/data:/var/www/FreshRSS/data"
      - "{{ nvme_mount_point }}/freshrss/extensions:/var/www/FreshRSS/extensions"
    ports:
      - "8888:80"
    env:
      TZ: "Europe/Berlin"
      CRON_MIN: "2,32"
    dns_servers:
      - "{{ local_ipv4 }}"