- name: add btrfs subvolume for Homepage
  community.general.btrfs_subvolume:
    name: /homepage
    state: present
    filesystem_label: "{{ nvme_filesystem_label }}"

- name: deploy Homepage
  community.docker.docker_container:
    name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart_policy: unless-stopped
    ports:
      - "3010:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ nvme_mount_point }}:{{ nvme_mount_point }}"
      - "{{ hdd_mount_point }}:{{ hdd_mount_point }}"
      - "{{ nvme_mount_point }}/homepage/config:/app/config"

- name: create Homepage config directory
  ansible.builtin.file:
    path: "{{ nvme_mount_point }}/homepage/config"
    state: directory
    mode: 0755

- name: copy Homepage config files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ nvme_mount_point }}/homepage/config/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: "homepage_custom.js", dest: "custom.js" }
    - { src: "homepage_settings.yaml", dest: "settings.yaml" }
    - { src: "homepage_bookmarks.yaml", dest: "bookmarks.yaml" }

- name: copy Homepage template configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ nvme_mount_point }}/homepage/config/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: "homepage_services.j2", dest: "services.yaml"}
    - { src: "homepage_widgets.j2", dest: "widgets.yaml" }