- name: Docker
  ansible.builtin.import_tasks:
    file: install.yml

- name: Watchtower
  ansible.builtin.import_tasks:
    file: watchtower.yml

- name: Nginx Proxy Manager
  ansible.builtin.import_tasks:
    file: npm.yml

- name: Komga
  ansible.builtin.import_tasks:
    file: komga.yml

- name: Syncthing
  ansible.builtin.import_tasks:
    file: syncthing.yml

- name: Actual Budget
  ansible.builtin.import_tasks:
    file: actual.yml

- name: Immich
  ansible.builtin.import_tasks:
    file: immich.yml

- name: Nextcloud
  ansible.builtin.import_tasks:
    file: nextcloud.yml