- name: Docker
  ansible.builtin.import_tasks:
    file: install.yml

- name: Watchtower
  ansible.builtin.import_tasks:
    file: watchtower.yml

- name: Nginx Proxy Manager
  ansible.builtin.import_tasks:
    file: npm.yml

- name: Komga
  ansible.builtin.import_tasks:
    file: komga.yml

- name: Actual Budget
  ansible.builtin.import_tasks:
    file: actual.yml

- name: Immich
  ansible.builtin.import_tasks:
    file: immich.yml

- name: Nextcloud
  ansible.builtin.import_tasks:
    file: nextcloud.yml

- name: Uptime Kuma
  ansible.builtin.import_tasks:
    file: uptime.yml
    
- name: Homepage
  ansible.builtin.import_tasks:
    file: homepage.yml

- name: Home Assistant
  ansible.builtin.import_tasks:
    file: homeassistant.yml

- name: Protonmail Bridge
  ansible.builtin.import_tasks:
    file: protonmail-bridge.yml

- name: Pi-hole
  ansible.builtin.import_tasks:
    file: pihole.yml

- name: FreshRSS
  ansible.builtin.import_tasks:
    file: freshrss.yml

- name: Paperless
  ansible.builtin.import_tasks:
    file: paperless.yml

- name: dufs
  ansible.builtin.import_tasks:
    file: dufs.yml