- name: add btrfs subvolume for Nginx Proxy Manager
  community.general.btrfs_subvolume:
    name: /nginx-proxy-manager
    state: present
    filesystem_label: "{{ nvme_filesystem_label }}"

- name: create Nginx Proxy Manager network
  community.docker.docker_network:
    name: npm-network
    state: present

- name: deploy Nginx Proxy Manager
  community.docker.docker_container:
    name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart_policy: unless-stopped
    volumes:
      - "{{ nvme_mount_point }}/nginx-proxy-manager/data:/data"
      - "{{ nvme_mount_point }}/nginx-proxy-manager/etc/letsencrypt:/etc/letsencrypt"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - name: npm-network