- name: add btrfs subvolumes for Pi-Hole
  community.general.btrfs_subvolume:
    name: /pihole
    state: present
    filesystem_label: "{{ nvme_filesystem_label }}" 

- name: copy systemd-resolved config file
  ansible.builtin.copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-resolved

- name: deploy Pi-Hole
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:latest
    restart_policy: unless-stopped
    volumes:
      - "{{ nvme_mount_point }}/pihole/etc-pihole:/etc/pihole"
      - "{{ nvme_mount_point }}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    ports:
      - "{{ local_ipv4 }}:53:53/tcp"
      - "{{ local_ipv4 }}:53:53/udp"
      - "90:80/tcp"
    env:
      TZ: Europe/Berlin
      WEBPASSWORD: "{{ pihole_admin_password }}"
      FTLCONF_LOCAL_IPV4: "{{ local_ipv4 }}"
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"

- name: change pihole-FTL.conf to allow Apple Private Relay
  ansible.builtin.lineinfile:
    path: "{{ nvme_mount_point }}/pihole/etc-pihole/pihole-FTL.conf"
    regexp: "^BLOCK_ICLOUD_PR=false"
    line: "BLOCK_ICLOUD_PR=false"