- name: add btrfs subvolumes for Protonmail Bridge
  community.general.btrfs_subvolume:
    name: /protonmail-bridge
    state: present
    filesystem_label: "{{ nvme_filesystem_label }}"

- name: deploy Protonmail Bridge
  community.docker.docker_container:
    name: protonmail-bridge
    image: shenxn/protonmail-bridge:latest
    restart_policy: unless-stopped
    volumes:
      - "{{ nvme_mount_point }}/protonmail-bridge:/root"
    ports:
      - "1025:25/tcp"
      - "1143:143/tcp"
    networks:
      - name: nextcloud-network