- name: add btrfs subvolume for Syncthing
  community.general.btrfs_subvolume:
    name: /syncthing
    state: present
    filesystem_label: "{{ nvme_filesystem_label }}"

- name: open Syncthing ports
  ansible.builtin.firewalld:
    port: 8384/tcp
    permanent: yes
    state: enabled
    immediate: true

- name: deploy Syncthing
  community.docker.docker_container:
    name: syncthing
    image: syncthing/syncthing:latest
    restart_policy: unless-stopped
    volumes:
      - "{{ nvme_mount_point }}/syncthing/st-sync:/var/syncthing"
    network_mode: host