- name: deploy Watchtower
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env:
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: "{{ watchtower_notification_url }}"
      WATCHTOWER_SCHEDULE: "0 0 4 * * *" # every day at 04:00