- name: copy hyfetch config file
  ansible.builtin.copy:
    src: hyfetch.json
    dest: "/home/{{ username }}/.config/hyfetch.json"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: copy message of the day script
  ansible.builtin.copy:
    src: motd.sh
    dest: /etc/profile.d/motd.sh
    owner: root
    group: root
    mode: 0755