- name: set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: install packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest

- name: check for core package updates
  ansible.builtin.command: dnf needs-restarting -r
  register: needs_restarting
  failed_when: false
  changed_when: false

- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 600
    connect_timeout: 600
    msg: "rebooting to apply core package updates"
  when: needs_restarting.rc != 0

- name: disable SSH password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: restart sshd

- name: enable passwordless sudo for {{ username }}
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  notify: restart sshd