- name: set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: change configuration for DNF
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      max_parallel_downloads=10
      fastestmirror=True
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: install packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest

- name: check for core package updates
  ansible.builtin.command: dnf needs-restarting -r
  register: needs_restarting
  failed_when: false
  changed_when: false

- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 600
    connect_timeout: 600
    msg: "rebooting to apply core package updates"
  when: needs_restarting.rc != 0

- name: create SSH config
  ansible.builtin.copy:
    src: ssh_config
    dest: "/home/{{ username }}/.ssh/config"
    owner: "{{ username}}"
    group: "{{ username }}"
    mode: 0644
  notify: restart sshd

- name: disable SSH password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: restart sshd

- name: enable passwordless sudo for {{ username }}
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  notify: restart sshd

- name: copy hyfetch config file
  ansible.builtin.copy:
    src: hyfetch.json
    dest: "/home/{{ username }}/.config/hyfetch.json"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: copy message of the day script
  ansible.builtin.copy:
    src: motd.sh
    dest: /etc/profile.d/motd.sh
    owner: root
    group: root
    mode: 0755

- name: generate ssh keypair
  ansible.builtin.openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_ed25519"
    type: ed25519
    owner: "{{ username }}"
    group: "{{ username }}"