- name: Basic
  ansible.builtin.import_tasks:
    file: basic.yml

- name: Packages
  ansible.builtin.import_tasks:
    file: packages.yml

- name: SSH
  ansible.builtin.import_tasks:
    file: ssh.yml

- name: Greeting
  ansible.builtin.import_tasks:
    file: greeting.yml

- name: Mail
  ansible.builtin.import_tasks:
    file: mail.yml