- name: set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: install packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest

- name: disable SSH password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: restart sshd

- name: enable passwordless sudo for {{ username }}
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  notify: restart sshd

- name: create docker group
  ansible.builtin.group:
    name: "{{ docker_group }}"
    gid: 2000
    state: present

- name: create docker user
  ansible.builtin.user:
    name: "{{ docker_user }}"
    uid: 2000
    state: present